chown munin:nobody -R ../
chmod g+w -R ../
chown apache:nobody -R ./uploads/
chmod g+w -R ./uploads/
chown apache:nobody -R ./done/
chmod g+w -R ./done/
chown apache:nobody -R ./error/
chmod g+w -R ./error/
setfacl -Rm g:nobody:rwX,d:g:nobody:rwX /var/www/html/mindparser/scripts/uploads/
